### ISSUE TITLE
Release for scalacheck 1.17.0?

### ISSUE THREAD

**Issue by mdedetrich** [rallyhealth/scalacheck-ops#52]
Scalacheck 1.16.0 and 1.17.0 has been released, would it be possible to publish scalacheck-ops for these versions?

You can see the releases here

- https://github.com/typelevel/scalacheck/releases/tag/v1.16.0
- https://github.com/typelevel/scalacheck/releases/tag/v1.17.0

**Comment by mdedetrich** [comment]
So scalacheck-ops was just released with 1.16.0, still need to do 1.17.0 however we are blocked due to scalatest not releasing a scalacheck ops for 1.17.

**Comment by jeffmay** [comment]
I think scalacheck >1.15.0 is actually backwards compatible at the binary level now. I think it should be safe to upgrade to the latest version of scalacheck without scalatest doing the same.

In fact, given this change in guarantees, we may want to consider only publishing breaking upgrades as separate artifacts and having a trunk artifact that always upgrades to the latest version of scalacheck.

**Comment by jeffmay** [comment]
As a possible option, we could publishing the version for ScalaCheck 1.16.0 as `scalacheck-ops` (without the scalacheck axis) and then publish another minor version bump that uses ScalaCheck 1.17.0. This way, we don't have to maintain a new artifact for every minor version bump of scalacheck.

**Comment by mdedetrich** [comment]
> I think scalacheck >1.15.0 is actually backwards compatible at the binary level now. I think it should be safe to upgrade to the latest version of scalacheck without scalatest doing the same.

Ah yes you are right, I forgot that its under typlevel and hence has bincompat guarantees. Will close issue.
