### ISSUE TITLE
Missing Scala.js/Scala.native artifacts for 1_15 and 1_16

### ISSUE THREAD

**Issue by mdedetrich** [rallyhealth/scalacheck-ops#60]
Something seems to have been broken with the CI process whereby the scala.js/scala-native artifacts for 1_15 and 1_16 haven't been deployed, see https://mvnrepository.com/artifact/com.rallyhealth/scalacheck-ops_1-15 and https://mvnrepository.com/artifact/com.rallyhealth/scalacheck-ops_1-16.

I think the issue may have been due to the ordering of the PR merges, in which case the scala.js/native 1-15 and 1-16 artifacts need to published manually in sbt shell. Alternately we can just make a new release, if this is the case then I have a new feature that I want to implement in the next few days and I don't need the artifacts so we can do another release after that feature.

@jeffmay I believe you were responsible for the release changes?

**Comment by jeffmay** [comment]
Yea, my workflow was totally broken when I pushed the 2.10.0 tag. I have reported the [issue on the sbt-github-actions](https://github.com/djspiewak/sbt-github-actions/issues/118) project and created a custom workflow for the time being in https://github.com/rallyhealth/scalacheck-ops/pull/63

**Comment by jeffmay** [comment]
@mdedetrich  This is fixed in https://github.com/rallyhealth/scalacheck-ops/releases/tag/v2.11.0
